name: total_tally
description: "for shopping price sum"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
#  sdk: '>=3.2.3 <4.0.0'
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any # 포멧등 패키지

  shared_preferences: ^2.0.13 # shared_preferences
  sqflite: ^2.0.0+3
  path: ^1.8.1
  provider: 6.0.3

  firebase_core: ^2.17.0
  cloud_firestore: 4.0.5

  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
